# This workflow will deploy the custom back-up container

name: Docker Mongodump CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push image
      uses: docker/build-push-action@v3
      with:
        context: ./integration
        push: true
          # TODO: We should not blindly use 'latest' here but a proper version.
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/docker-mongodump:latest
